### ISSUE TITLE
データ由来は、国土数値情報ではなく、位置参照情報である

### ISSUE THREAD

**Issue by nyampire** [geolonia/japanese-addresses#1]
README.mdおよびウェブサイト上の表記で、元データとして`国土数値情報`が参照されていますが、正しくは`位置参照情報`です。

リンク先のURLは正しいようなので、文章部分の修正が必要です。

**Comment by miya0001** [comment]
ありがとうございます！

**Comment by miya0001** [comment]
以下のコミットで修正。

https://github.com/geolonia/japanese-addresses/commit/233f2a07061fa3b258494eb8a4d8d022c0682c80
