### ISSUE TITLE
千葉県茂原市大芝と千葉県八千代市緑が丘西について

### ISSUE THREAD

**Issue by jumpei-nishioka** [geolonia/japanese-addresses#10]
はじめまして。
とても良い取り組みをされていて大変ありがたく思います。

データを利用するうちに気がついたのですが、
千葉県茂原市大芝についてですが、実際には1丁目〜3丁目があるはずですが、
データにはなさそうです。

千葉県八千代市緑が丘はあったのを確認したのですが、千葉県八千代市緑が丘西については
なさそうです。

お手すきにでも、確認していただけると嬉しいです。
よろしくおねがいします。

**Comment by miya0001** [comment]
ありがとうございます！

**Comment by champierre** [comment]
緑が丘西一〜八丁目はすでに追加されていました。 https://geolonia.github.io/japanese-addresses/api/ja/%E5%8D%83%E8%91%89%E7%9C%8C/%E5%85%AB%E5%8D%83%E4%BB%A3%E5%B8%82.json

千葉県茂原市大芝一丁目〜三丁目は追加します。

**Comment by champierre** [comment]
https://github.com/geolonia/japanese-addresses/pull/35 で対応しました。
