### ISSUE TITLE
千葉県流山市大字鰭ケ崎について

### ISSUE THREAD

**Issue by jumpei-nishioka** [geolonia/japanese-addresses#11]
お世話になっております。
連続投稿失礼します。

```
"12","千葉県","チバケン","CHIBA KEN","12220","流山市","ナガレヤマシ","NAGAREYAMA SHI","122200024000","大字鰭ケ崎","35.841674","139.912205"
"12","千葉県","チバケン","CHIBA KEN","12220","流山市","ナガレヤマシ","NAGAREYAMA SHI","122200043000","鰭ケ崎","35.839606","139.908472"
```

千葉県流山市大字鰭ケ崎についてですが、データに大字が含まれているものと含まれていないものの2件存在しているみたいです。（緯度経度も確認しましたが鰭ケ崎内のそう遠くない地域でした。）
お手すきに確認よろしくお願いします。

**Comment by miya0001** [comment]
ありがとうございます！
ご参考までにお伺いしたいのですが、`大字` とか `字` は消してしまおうか迷っているのですが、どう思われますか？

Related #7

**Comment by jumpei-nishioka** [comment]
連絡ありがとうございます。
大字と字の扱いは悩ましいですね。。
他のオープンデータでも揺れてしまっているので良く大字や字を置換しているコードを書いているので、
消していただけると助かります。

**Comment by champierre** [comment]
@jumpei-nishioka ご指摘いただいてから随分時間が経ってしまいましたが、重複チェックの仕組みを入れ、千葉県流山市鰭ケ崎 のデータについては、以下のデータのみ latest.csv に含まれるように更新しました。

```
"12","千葉県","チバケン","CHIBA KEN","12220","流山市","ナガレヤマシ","NAGAREYAMA SHI","122200024000","大字鰭ケ崎","35.841674","139.912205"
```
