### ISSUE TITLE
神奈川県川崎市宮前区西野川について

### ISSUE THREAD

**Issue by jumpei-nishioka** [geolonia/japanese-addresses#14]
お世話になっております。

最新のデータを確認したところ、神奈川県川崎市宮前区の「野川本町１・２丁目」「西野川１〜３丁目」が不足しているみたいです。
お手数ですがご確認よろしくおねがいします。

2019年に新しく追加された街名みたいです。
https://www.townnews.co.jp/0201/2019/10/11/501532.html

**Comment by miya0001** [comment]
ありがとうございます！

**Comment by jumpei-nishioka** [comment]
追加で申し訳ないのですが、気づいた地名の足りない所。

茨城県松並青葉の1丁目〜4丁目が抜けていると思います。
wikipediaによると2016年に追加されたみたいです。

神奈川県座間市入谷西が抜けています。（入谷東はありました。）
これも最近追加された地名だと思います。

お手数ですがご確認よろしくおねがいします。

**Comment by miya0001** [comment]
Note: API 側のみ神奈川県川崎市宮前区をアップデートした。

**Comment by champierre** [comment]
https://github.com/geolonia/japanese-addresses/pull/34 で対応しました。
