### ISSUE TITLE
住所データ追加/修正/削除のリクエスト

### ISSUE THREAD

**Issue by yagumaha** [geolonia/japanese-addresses#144]
お世話になっております。
以下の住所がないようなので追加していただけるとありがたいです。

# リクエストの種類(必須)

- [x] 追加
- [ ] 修正
- [ ] 削除

# 対象となる住所(必須)

- 愛知県みよし市黒笹山手
- 愛知県豊川市大木新町通

# 参考情報・URL(オプション)

自治体のホームページのURLなど、リクエストの根拠となる情報を教えて下さい。

https://www.kokudo.or.jp/place/pl2020_8.html
https://www.kokudo.or.jp/place/pl2020_1.html

# 備考(オプション)

その他補足情報が必要であればご記入ください。

**Comment by champierre** [comment]
@yagumaha 住所データの追加リクエストどうもありがとうございます。
v0.6.5 で反映させていただきましたのでご確認ください。

https://github.com/geolonia/japanese-addresses/releases/tag/v0.6.5

**Comment by yagumaha** [comment]
@champierre 
対応ありがとうございます！データ追加いただいたのを確認いたしました。
