### ISSUE TITLE
住所データ v2

### ISSUE THREAD

**Issue by miya0001** [geolonia/japanese-addresses#17]
以下の課題を解決したい。

* 継続的なメンテナンスが困難で地名変更に特に弱い。
* 網羅している住所が不十分。特に地番住所が弱い。

### データソースの変更

* 現状は、「位置参照情報の町丁目レベル」と「郵便番号データ」を使用している。
* 変更後は、**[電子国土基本図（地名情報）「住居表示住所」](https://www.gsi.go.jp/kihonjohochousa/jukyo_jusho.html)** と **[位置参照情報の「街区レベル」](https://nlftp.mlit.go.jp/cgi-bin/isj/dls/_choose_method.cgi)** をベースにしたい。
* 「カナ」、「ローマ字」のために、郵便番号データも使用する必要があると思う。

### 列の変更

現状のCSVは、以下のような構造になっている。

* 都道府県コード
* 都道府県名
* 都道府県名カナ
* 都道府県名ローマ字
* 市区町村コード
* 市区町村名
* 市区町村名カナ
* 市区町村名ローマ字
* 大字町丁目コード
* 大字町丁目名
* 緯度（代表点）
* 経度（代表点）

アップデート後は以下の通りとする。

* 都道府県コード
* 都道府県名
* 都道府県名カナ
* 都道府県名ローマ字
* 市区町村コード
* 市区町村名
* 市区町村名カナ
* 市区町村名ローマ字
* 大字町丁目名
* 大字町丁目名カナ
* 大字町丁目名ローマ字
* 小字
* 小字カナ
* 小字ローマ字

~※ 緯度経度及び大字町丁目名コードは削除する。~

注: その後のやり取りで緯度経度は残すことにした。

**Comment by miya0001** [comment]
* カナ及びローマ字はとりあえず中途半端でも可。クラウドソーシング等の人力で継続的にメンテナンスができるようにするための何かを検討したい。
* 大字町丁目名に含まれる「大字」という文字列は削除してほしい。（常に大字町丁目名の先頭にある？）
* カナ及びローマ字のデータソースで、郵便番号データよりももっと良いのがあれば検討したい。
* 文字のゆらぎに注意。ゆらぎがある場合、表記上どちらかが誤りの場合もある。
* `1丁目` の `1` は数字とする。ただし `壱丁目` の場合は漢字のままとする。

**Comment by miya0001** [comment]
電子国土基本図（地名情報）「住居表示住所」 と 位置参照情報の「街区レベル」 について
以下、僕の認識です。

* **電子国土基本図（地名情報）「住居表示住所」** は、住居表示住所はそれなりのデータであることを期待してもいいのではないかと思う。
* **位置参照情報の「街区レベル」** 壱参照情報は更新頻度が低いのが難点であったが、地番住所そのものの更新はほとんどないのではないか？

ありうる問題点としては、もともと存在していた地番住所が住居表示にかわり、結果的に地名が変わってケースで、なくなった地名と新しく増えた地名を突き合わせるのが困難になる。
これに対する機械的な処理はとてもむずかしいので、地名の辞書をつくることを最優先し、とりあえず重複してもしょうがないかなと思う。

**Comment by miya0001** [comment]
参考までに過去の課題も。
https://github.com/geolonia/japanese-addresses/pulls?q=is%3Apr+is%3Aclosed

**Comment by miya0001** [comment]
プロジェクト立てておきました。
https://github.com/geolonia/japanese-addresses/projects/1

**Comment by champierre** [comment]
都道府県コード
市区町村コード

は、電子国土基本図（地名情報）の街区レベルから取ってくる。

**Comment by champierre** [comment]
- 都道府県コード
- 市区町村コード

は、位置参照情報の「大字・町丁目レベル」から取ってくる。

**Comment by champierre** [comment]
大字と小字を連結したものを「大字町丁目名」にする

**Comment by miya0001** [comment]
「街区レベル」は住居表示が整備されていないと無い概念なので、「街区レベル」のデータでは住居表示が未整備の地域（地番住所しか無い地域）がすっぽり抜けるのですね。
なので、「大字・町丁目レベル」もマージしないといけないようです。

**Comment by ShinichiNishikawa** [comment]
Github Actions の上限はこちらでした。 https://docs.github.com/ja/actions/reference/usage-limits-billing-and-administration

**Comment by miya0001** [comment]
`大字`や`字`の取り扱いについては、国交省の位置参照情報等に追従したほうがいいみたい。
https://github.com/geolonia/normalize-japanese-addresses/pull/92

**Comment by miya0001** [comment]
Related: https://github.com/geolonia/japanese-addresses/issues/23

やはり緯度経度も入れたほうが良さそう。

**Comment by champierre** [comment]
data/latest_v2.csv -> data/latest.csv に統合したらこのタスクを終了とする。

**Comment by champierre** [comment]
@miya0001 この issue クローズしてもいいですか？

**Comment by champierre** [comment]
クローズします。もし問題あれば Reopen してください。 @miya0001
