### ISSUE TITLE
latest.csv のビルドが成功しない

### ISSUE THREAD

**Issue by kamataryo** [geolonia/japanese-addresses#170]
# バグの内容

- bin/build.js がエラーで停止する

# 再現手順

- data ディレクトリにキャッシュされている日本郵政のローマ字のデータを削除する
- node bin/build.js でビルドのスクリプトを実行する

# 本来どう動作すべきか

- ビルドが成功し、ローマ字のデータを正しく含む latest.csv 等の生成物ができる

## 原因と方針

日本郵政の csv のエンドポイントが変更されているためです。
この問題は、 #153 で記載したベースレジストリのデータに対応することにより解決される見込みです。
ベースレジストリの町字マスタにはフリガナが含まれているため、これからローマ字のデータを生成できます。
また、他のいくつかのイシューを解決できる見込みです。

**Comment by keichan34** [comment]
メジャーバージョンを新しく作ることによって一旦クローズ
