### ISSUE TITLE
[要望] 「大字町丁目名」について「町」と「町名」を分離したデータが欲しい

### ISSUE THREAD

**Issue by ctc-h-mineta** [geolonia/japanese-addresses#2]
掲題の件で要望となります

- 現在町+町名となってますが分離したカラムは可能でしょうか
- 字、大字の有無を判断するカラムが欲しいです

つきましてはご検討願えないでしょうか

**Comment by miya0001** [comment]
@ctc-h-mineta ありがとうございます！

> 現在町+町名となってますが分離したカラムは可能でしょうか

本データには、町丁名に対応した町丁目コードという列があり、現時点では難しいかなと考えています。

> 字、大字の有無を判断するカラムが欲しいです

今の時点ではそれを判別するためのデータソースがないので、難しいかなと思います。

**Comment by ctc-h-mineta** [comment]
返信が遅くなり申し訳ありません
即必要というわけではない為、検討して頂けると幸いです

必要に応じてこちらのissueはクローズしていただいても構いません

**Comment by champierre** [comment]
クローズします。
