### ISSUE TITLE
長野県上伊那郡南箕輪村のデータについて

### ISSUE THREAD

**Issue by yusuke-yaguchi** [geolonia/japanese-addresses#20]
お世話になっております。

最新のデータを確認したところ、上伊那郡南箕輪村のデータが不足しているみたいです。
お手数ですがご確認よろしくおねがいします。

**Comment by miya0001** [comment]
@yusuke-yaguchi ありがとうございます！

データを確認したところ、https://github.com/geolonia/japanese-addresses/pull/19 がマージされれば解決されると思いますのでしばらくお待ちいただけますと幸いです。

**Comment by champierre** [comment]
https://geolonia.github.io/japanese-addresses/api/ja/%E9%95%B7%E9%87%8E%E7%9C%8C/%E4%B8%8A%E4%BC%8A%E9%82%A3%E9%83%A1%E5%8D%97%E7%AE%95%E8%BC%AA%E6%9D%91.json に追加されています。

**Comment by champierre** [comment]
クローズします。もし問題あれば Reopen してください。 @miya0001
