### ISSUE TITLE
手動でのデータの追加方法を検討する

### ISSUE THREAD

**Issue by miya0001** [geolonia/japanese-addresses#21]
オープンデータでデータがない場合に手作業でデータを上書きするための方法を検討する。
たとえば、差分のみを保存したJSONを作成して、それを CSV 作成時や API のビルド時にマージするなど。

Related: #17

**Comment by champierre** [comment]
https://github.com/geolonia/japanese-addresses/pull/27 で対応しました。

**Comment by champierre** [comment]
GitHub Issue への投稿を、「承認」すれば patch.json に反映する仕組みを用意したい。
