### ISSUE TITLE
大字町丁目名カナ、大字町丁目名ローマ字の出力 (v2)

### ISSUE THREAD

**Issue by miya0001** [geolonia/japanese-addresses#22]
Related: #17 #19

**Comment by champierre** [comment]
https://github.com/geolonia/japanese-addresses/pull/25 で対応しました。

**Comment by champierre** [comment]
@miya0001 こちら対応済みなのでクローズしていいですか？

**Comment by miya0001** [comment]
ありがとうございます！！
