### ISSUE TITLE
緯度・経度もできれば入れたい (v2)

### ISSUE THREAD

**Issue by miya0001** [geolonia/japanese-addresses#23]
緯度・経度もできれば入れたい

**Comment by miya0001** [comment]
Related: https://github.com/geolonia/community-geocoder/issues/110

**Comment by champierre** [comment]
https://github.com/geolonia/japanese-addresses/pull/41 で緯度、軽度をAPIに追加しました。

**Comment by champierre** [comment]
@miya0001 この issue クローズしてもいいですか？

**Comment by champierre** [comment]
クローズします。もし問題あれば Reopen してください。 @miya0001
