### ISSUE TITLE
データが無い地名

### ISSUE THREAD

**Issue by miya0001** [geolonia/japanese-addresses#24]
以下のCSVのうち、2021/4/4 現在で町名が検出できなかった住所は以下の通り。
https://github.com/geolonia/normalize-japanese-addresses/blob/master/test/addresses.csv

* 神奈川県横浜市緑区中山５丁目１－２４
* 神奈川県川崎市宮前区西野川１丁目４０－２８
* 神奈川県川崎市宮前区南野川２丁目６２－２４
* 神奈川県川崎市宮前区西野川２丁目２９－４６
* 東京都新宿区三栄町２－８
* 東京都新宿区三栄町１７－１６

**Comment by miya0001** [comment]
`三栄町` は `四谷三栄町` として位置参照情報にある。

**Comment by miya0001** [comment]
三栄町問題は、たんなるゆらぎであるため `normalize-japanese-addresses` で対処した。
https://github.com/geolonia/normalize-japanese-addresses/commit/6908c71ba88164408d5dcbc9e6049ca946a6e09e

**Comment by jumpei-nishioka** [comment]
神奈川県宮前区野川関連で、野川台も追加されているのでこちらも併せて対応して頂けると嬉しかったりします。
https://www.city.kawasaki.jp/250/page/0000115998.html

**Comment by champierre** [comment]
https://github.com/geolonia/japanese-addresses/pull/27 で対応しました。

本 issue で指摘されている住所を含め、同時期に追加された以下の住所を追加しています。

神奈川県横浜市緑区中山5丁目
神奈川県横浜市緑区中山6丁目
神奈川県川崎市宮前区野川本町1丁目
神奈川県川崎市宮前区野川本町2丁目
神奈川県川崎市宮前区西野川1丁目
神奈川県川崎市宮前区西野川2丁目
神奈川県川崎市宮前区西野川3丁目
神奈川県川崎市宮前区野川台1丁目
神奈川県川崎市宮前区野川台2丁目
神奈川県川崎市宮前区野川台3丁目
神奈川県川崎市宮前区南野川1丁目
神奈川県川崎市宮前区南野川2丁目
神奈川県川崎市宮前区南野川3丁目

**Comment by jumpei-nishioka** [comment]
埼玉県北足立郡伊奈町大字小室が北足立郡伊奈町中央一丁目〜五丁目に町名変更になったみたいです。
お手隙にて確認お願いします。
https://www.town.saitama-ina.lg.jp/cmsfiles/contents/0000005/5863/oshirase-panf.pdf

**Comment by miya0001** [comment]
@jumpei-nishioka ありがとうございます。ご連絡いただいた地名については別Issueを立てました。
https://github.com/geolonia/japanese-addresses/issues/32
