### ISSUE TITLE
埼玉県北足立郡伊奈町大字小室が北足立郡伊奈町中央一丁目〜五丁目に町名変更

### ISSUE THREAD

**Issue by miya0001** [geolonia/japanese-addresses#32]
https://github.com/geolonia/japanese-addresses/issues/24#issuecomment-826445364

**Comment by champierre** [comment]
staging の api には追加されました。

https://geolonia.github.io/japanese-addresses/staging-api/ja/%E5%9F%BC%E7%8E%89%E7%9C%8C/%E5%8C%97%E8%B6%B3%E7%AB%8B%E9%83%A1%E4%BC%8A%E5%A5%88%E7%94%BA.json
