### ISSUE TITLE
小字の列及びAPIを追加する

### ISSUE THREAD

**Issue by miya0001** [geolonia/japanese-addresses#36]
小字に含まれる`字`のゆらぎを正しく正規化することが難しいため、現状、町丁目（大字）と小字は一つの列に合体させているが、小字は独立した列にしたい。

Related: https://github.com/geolonia/normalize-japanese-addresses/pull/96

**Comment by champierre** [comment]
https://github.com/geolonia/japanese-addresses/pull/45 で小字を独立した列にしました。

**Comment by champierre** [comment]
@miya0001 この issue クローズしてもいいですか？

**Comment by champierre** [comment]
クローズします。もし問題あれば Reopen してください。 @miya0001
