### ISSUE TITLE
住所データ v2 リリースチェックリスト

### ISSUE THREAD

**Issue by miya0001** [geolonia/japanese-addresses#50]
- [x] `latest.csv` への一本化(https://github.com/geolonia/japanese-addresses/pull/48 のマージ)
- [x] API のアップデート（緯度経度が含まれる JSON へのアップデートを行う？）
- [x] 緯度経度が含まれる API へアップデートを行う場合には、NJA のアップデートも行う
- [x] NJA のアップデートに伴う不動産 ID 側のアップデートが必要であればそれも
- [x] ブログの公開
- [x] 住所データの README のアップデート(https://github.com/geolonia/japanese-addresses/pull/47 のマージ)
- [x] 関連する Issue のクローズ

**Comment by miya0001** [comment]
@keichan34 @champierre 
他にもあれば追記お願いします。

**Comment by champierre** [comment]
@miya0001 関連するPRへのリンクを追加しておきました。

「API のアップデート（緯度経度が含まれる JSON へのアップデートを行う？）」については、すでに develop のブランチにはマージ済みなので、tag をつけて S3 の方にあがっているバージョンに接続してもらえばテストできるようになっているかと思います。 -> @keichan34

**Comment by keichan34** [comment]
不動産IDのアップデートをリリースしたので、こっちのlatest.csvをいつでも更新してもいいという認識です :bow:

**Comment by champierre** [comment]
@keichan34 それでは https://github.com/geolonia/japanese-addresses/pull/48 をマージしますね。もし問題が発生したらいつでも戻します。

**Comment by champierre** [comment]
@miya0001 この issue クローズしてもいいですか？

**Comment by champierre** [comment]
クローズします。もし問題あれば Reopen してください。 @miya0001
