### ISSUE TITLE
緯度・経度に文字列型と数値型が混在している

### ISSUE THREAD

**Issue by ksasao** [geolonia/japanese-addresses#57]
# バグの内容

- latest.csv の緯度・経度に文字列型(""あり)と数値型(""なし)が混在しています。

# 再現手順

- latest.csv をダウンロードする。
- latest.csv を開き、29278行目付近を表示すると以下のようになっています。ファイルの複数箇所にこのような揺れがみられます。

```csv
"02","青森県","アオモリケン","AOMORI KEN","02450","三戸郡新郷村","サンノヘグンシンゴウムラ","SANNOHE GUN SHINGO MURA","大字戸来",,,,40.453328,141.112886
"02","青森県","アオモリケン","AOMORI KEN","02201","青森市","アオモリシ","AOMORI SHI","浪岡大字下石川",,,"岡田","40.734852","140.532559"
```

# 本来どう動作すべきか

- 緯度・経度は数値型(""なし)に統一していただけるとありがたいです。

**Comment by champierre** [comment]
ご指摘ありがとうございます。

https://github.com/geolonia/japanese-addresses/pull/58

上記PRで対応して修正しました。緯度・経度は数値型で統一しました。

**Comment by ksasao** [comment]
latest.csv の緯度・経度がすべて数値型になっていることを確認しました。ご対応いただきありがとうございました。
