### ISSUE TITLE
住所データ追加のリクエスト

### ISSUE THREAD

**Issue by jumpei-nishioka** [geolonia/japanese-addresses#59]
# リクエストの種類(必須)

- [x] 追加
- [ ] 修正
- [ ] 削除

# 対象となる住所(必須)

- 千葉市中央区都町４丁目
- 千葉市中央区都町５丁目
- 千葉市中央区都町６丁目
- 千葉市中央区都町７丁目
- 千葉市中央区都町８丁目

# 参考情報・URL(オプション)

https://www.city.chiba.jp/shimin/shimin/kusei/31miyako.html

**Comment by champierre** [comment]
@jumpei-nishioka 住所の追加のリクエストありがとうございます。リクエストにお応えして追加しましたのでお知らせいたします。

**Comment by jumpei-nishioka** [comment]
@champierre ありがとうございますー。
