### ISSUE TITLE
住所データ追加/修正/削除のリクエスト

### ISSUE THREAD

**Issue by jumpei-nishioka** [geolonia/japanese-addresses#63]
# リクエストの種類(必須)

- [x] 追加
- [ ] 修正
- [ ] 削除

# 対象となる住所(必須)

千葉県袖ケ浦市袖ケ浦駅前１丁目
千葉県袖ケ浦市袖ケ浦駅前２丁目
神奈川県足柄上郡大井町大井中央
茨城県つくば市流星台

# 参考情報・URL(オプション)

自治体のホームページのURLなど、リクエストの根拠となる情報を教えて下さい。

https://www.city.sodegaura.lg.jp/soshiki/toshi/sodegauraekiumigawatotikukakuseirijigyou.html
https://www.town.oi.kanagawa.jp/soshiki/11/kukakuseiri-kanchi.html
https://www.city.tsukuba.lg.jp/jigyosha/machinami/ensen/ensenkaihatsu/1005770.html

# 備考(オプション)

その他補足情報が必要であればご記入ください。

**Comment by champierre** [comment]
@jumpei-nishioka 住所の追加のリクエストありがとうございます。リクエストにお応えして追加しましたのでお知らせいたします。

**Comment by jumpei-nishioka** [comment]
ありがとうございます！
