### ISSUE TITLE
住所データ追加/修正/削除のリクエスト

### ISSUE THREAD

**Issue by GandF-TakaakiSugie** [geolonia/japanese-addresses#65]
# リクエストの種類(必須)

- [ ] 追加
- [o ] 修正
- [ ] 削除

# 対象となる住所(必須)

- 東京都豊島区南池袋四丁目NULL (koazaにNULLと言う文字が入っていました)
 

# 参考情報・URL(オプション)

自治体のホームページのURLなど、リクエストの根拠となる情報を教えて下さい。

- (例) https://www.city.yokohama.lg.jp/kurashi/koseki-zei-hoken/todokede/jukyo/kako/jisshi-r1.html

# 備考(オプション)

その他補足情報が必要であればご記入ください。

**Comment by champierre** [comment]
@GandF-TakaakiSugie 住所の修正のリクエストありがとうございます。リクエストにお応えして latest.csv を更新しましたのでお知らせいたします。

**Comment by GandF-TakaakiSugie** [comment]
ご対応、ありがとうございます
