### ISSUE TITLE
住所データ追加/修正/削除のリクエスト

### ISSUE THREAD

**Issue by okadatsuneo** [geolonia/japanese-addresses#68]
# リクエストの種類(必須)

- [○] 追加
- [ ] 修正
- [ ] 削除

# 対象となる住所(必須)

- 東京都江東区海の森一丁目
- 東京都江東区海の森二丁目
- 東京都江東区海の森三丁目

# 参考情報・URL(オプション)

自治体のホームページのURLなど、リクエストの根拠となる情報を教えて下さい。

- https://www.city.koto.lg.jp/060301/kurashi/sumai/jyuukyohyouji.html

**Comment by champierre** [comment]
@okadatsuneo 住所の追加リクエストありがとうございます。リクエストにお応えして latest.csv を更新しましたのでお知らせいたします。
