### ISSUE TITLE
住所データ追加/修正/削除のリクエスト

### ISSUE THREAD

**Issue by okadatsuneo** [geolonia/japanese-addresses#69]
# リクエストの種類(必須)

- [○] 追加
- [ ] 修正
- [ ] 削除

# 対象となる住所(必須)

- 東京都大田区令和島一丁目
- 東京都大田区令和島二丁目

# 参考情報・URL(オプション)

- https://www.city.ota.tokyo.jp/oshirase/mokutekibetsu/koseki/machikuikishinsetsu.html

**Comment by champierre** [comment]
@okadatsuneo 住所の追加リクエストありがとうございます。リクエストにお応えして latest.csv を更新しましたのでお知らせいたします。

**Comment by okadatsuneo** [comment]
追加ありがとうございました。
