### ISSUE TITLE
利用・改変時のライセンス表記についての質問です

### ISSUE THREAD

**Issue by wakamezake** [geolonia/japanese-addresses#8]
こちらデータセットについての質問ではなく、データセットを利用する場合、改変した場合のライセンス表記についての質問になります。

以下URL、CC JapanのFAQ　よくある質問と回答に記載されている
> CCライセンスの作品を利用する際、何を記載すればよいのでしょうか？　また、CCライセンスのURLやアイコン、バナー等も表示しなければならないのでしょうか？
> 元の作品の作者名、スポンサー、タイトル
参考: https://creativecommons.jp/faq/#a6

という質問内に記載されてあります、元の作品の作者名はどなたを明記すればよいでしょうか。

**Comment by miya0001** [comment]
改変して再配布する場合は、 [Geolonia 住所データ](https://geolonia.github.io/japanese-addresses/) でいいと理解していますが、もし間違っていたらすいません。

**Comment by miya0001** [comment]
以下のページの出典の部分も記載していただければ間違いないとは思います。

**Comment by wakamezake** [comment]
回答ありがとうございます。
