### ISSUE TITLE
住所データ追加のリクエスト

### ISSUE THREAD

**Issue by sakisaitomn** [geolonia/japanese-addresses#97]
# リクエストの種類(必須)
- [x] 追加
- [ ] 修正
- [ ] 削除

# 対象となる住所(必須)
- 長野県上伊那郡南箕輪村の市区町村コード13件が抜けていました

# 参考情報・URL(オプション)

おそらく上記の市区町村コードは下記より「20385」になると思います

- https://www.e-sale24.com/

# 備考(オプション)

その他補足情報が必要であればご記入ください。
- 特になし

**Comment by champierre** [comment]
@sakisaitomn ご指摘ありがとうございます。修正して、長野県上伊那郡南箕輪村の市区町村コードを入れるようにしました。

**Comment by sakisaitomn** [comment]
@champierre ご対応ありがとうございました！ 🙇
